sudo: false

language: c

env:
  - GHCVER=7.8.4
  - GHCVER=7.10.3
  - GHCVER=8.0.2
  - GHCVER=8.2.2
  - GHCVER=8.4.4
  - GHCVER=8.6.3

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.4
      - ghc-7.10.3
      - ghc-8.0.2
      - ghc-8.2.2
      - ghc-8.4.4
      - ghc-8.6.3
      - happy-1.19.5
      - cabal-install-2.4

before_install:
  - export PATH=$HOME/.tinc/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/2.4/bin:/opt/happy/1.19.5/bin:$PATH
  - curl -sSL https://github.com/sol/tinc/raw/master/get-tinc.sh | bash
  - tinc --version
  - ghc --version
  - cabal --version
  - happy --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config

install:
  - tinc
  - (cd hspec-wai-json && tinc)

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
  - (cd hspec-wai-json && cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test)
  - (cd hspec-wai-json && cabal exec -- doctest -isrc src/Test/Hspec/Wai/JSON.hs)
  - (cd hspec-wai-json && echo main | cabal exec -- ghci ../README.lhs)

cache:
  directories:
    - $HOME/.tinc/cache
